[package]
name = "syscall"
version = "0.1.0"
authors = ["gary.fan <1779905848@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="syscall"

[dependencies]
bitflags="1.1.0"
